// File generated by FlutterFire CLI.
// Run: flutterfire configure
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDt1NvPerlWb2rlEpg3l_bD88Hc__5GqJI',
    appId: '1:83467342479:web:d9d4a268596f23dac016fa',
    messagingSenderId: '83467342479',
    projectId: 'yaaram-80842',
    authDomain: 'yaaram-80842.firebaseapp.com',
    storageBucket: 'yaaram-80842.firebasestorage.app',
    measurementId: 'G-6NKBGW631M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBd26r9-6yv-buuTMomWoJQ4Aat7TM5Azw',
    appId: '1:83467342479:android:474e5a9fc4381b15c016fa',
    messagingSenderId: '83467342479',
    projectId: 'yaaram-80842',
    storageBucket: 'yaaram-80842.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'yaaram',
    storageBucket: 'yaaram.firebasestorage.app',
    iosBundleId: 'com.yaaram.lovestory',
  );
}
